fragment memberDetails on Member {
  id
  address
  username
  usernameFormatted
  displayName
}

fragment memberPayloadDetails on MemberPayload {
  member {
    ...memberDetails
  }
  error {
    ...userErrorDetails
  }
}
